// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(CMContext))]
    [Migration("20250602170803_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId")
                        .HasName("AspNetUserRoles_pkey");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("backend.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id")
                        .HasName("AspNetRoles_pkey");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("backend.Models.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("AspNetRoleClaims_pkey");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("backend.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool?>("IsStudent")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsTeacher")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp(6) without time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id")
                        .HasName("AspNetUsers_pkey");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("backend.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id")
                        .HasName("AspNetUserClaims_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("backend.Models.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("AspNetUserLogins_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("backend.Models.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("AspNetUserTokens_pkey");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("backend.Models.Course", b =>
                {
                    b.Property<string>("CourseId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp(6) with time zone");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp(6) with time zone");

                    b.Property<int?>("MaxStudentQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Price")
                        .HasPrecision(15, 5)
                        .HasColumnType("numeric(15,5)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp(6) with time zone");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("TeacherId ");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp(6) with time zone");

                    b.Property<string>("UpdatedUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("CourseId")
                        .HasName("Courses_pkey");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("backend.Models.CourseStudent", b =>
                {
                    b.Property<string>("CourseStudentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp(6) without time zone");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp(6) without time zone");

                    b.Property<string>("UpdatedUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("CourseStudentId")
                        .HasName("CourseStudents_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("CourseStudents");
                });

            modelBuilder.Entity("backend.Models.Room", b =>
                {
                    b.Property<string>("RoomId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp(6) with time zone");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp(6) with time zone");

                    b.Property<string>("UpdatedUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("RoomId")
                        .HasName("Rooms_pkey");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("backend.Models.RoomCourse", b =>
                {
                    b.Property<string>("RoomCourseId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp(6) without time zone");

                    b.Property<string>("CreatedUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp(6) without time zone");

                    b.Property<string>("UpdatedUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("RoomCourseId")
                        .HasName("RoomCourses_pkey");

                    b.HasIndex("CourseId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomCourses");
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("backend.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("AspNetUserRoles_RoleId_fkey");

                    b.HasOne("backend.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("AspNetUserRoles_UserId_fkey");
                });

            modelBuilder.Entity("backend.Models.AspNetRoleClaim", b =>
                {
                    b.HasOne("backend.Models.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("AspNetRoleClaims_RoleId_fkey");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("backend.Models.AspNetUserClaim", b =>
                {
                    b.HasOne("backend.Models.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("AspNetUserClaims_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.AspNetUserLogin", b =>
                {
                    b.HasOne("backend.Models.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("AspNetUserLogins_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.AspNetUserToken", b =>
                {
                    b.HasOne("backend.Models.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("AspNetUserTokens_UserId_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Course", b =>
                {
                    b.HasOne("backend.Models.AspNetUser", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("Courses_TeacherId _fkey");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("backend.Models.CourseStudent", b =>
                {
                    b.HasOne("backend.Models.Course", "Course")
                        .WithMany("CourseStudents")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("CourseStudents_CourseId_fkey");

                    b.HasOne("backend.Models.AspNetUser", "Student")
                        .WithMany("CourseStudents")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("CourseStudents_StudentId_fkey");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("backend.Models.RoomCourse", b =>
                {
                    b.HasOne("backend.Models.Course", "Course")
                        .WithMany("RoomCourses")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("RoomCourses_CourseId_fkey");

                    b.HasOne("backend.Models.Room", "Room")
                        .WithMany("RoomCourses")
                        .HasForeignKey("RoomId")
                        .IsRequired()
                        .HasConstraintName("RoomCourses_RoomId_fkey");

                    b.Navigation("Course");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("backend.Models.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("backend.Models.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");

                    b.Navigation("CourseStudents");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("backend.Models.Course", b =>
                {
                    b.Navigation("CourseStudents");

                    b.Navigation("RoomCourses");
                });

            modelBuilder.Entity("backend.Models.Room", b =>
                {
                    b.Navigation("RoomCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
